[package]
name = "ortho-games/moonplayer"
description = "A fork of maximumadhd/moonlite built with synchronization in mind."
version = "0.1.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.1"
Janitor = "howmanysmall/janitor@1.16.0"
